################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk/platform/service/sleeptimer/src/sl_sleeptimer.c \
C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk/platform/service/sleeptimer/src/sl_sleeptimer_hal_burtc.c \
C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk/platform/service/sleeptimer/src/sl_sleeptimer_hal_prortc.c \
C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk/platform/service/sleeptimer/src/sl_sleeptimer_hal_rtcc.c \
C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk/platform/service/sleeptimer/src/sl_sleeptimer_hal_timer.c 

OBJS += \
./gecko_sdk_4.3.0/platform/service/sleeptimer/src/sl_sleeptimer.o \
./gecko_sdk_4.3.0/platform/service/sleeptimer/src/sl_sleeptimer_hal_burtc.o \
./gecko_sdk_4.3.0/platform/service/sleeptimer/src/sl_sleeptimer_hal_prortc.o \
./gecko_sdk_4.3.0/platform/service/sleeptimer/src/sl_sleeptimer_hal_rtcc.o \
./gecko_sdk_4.3.0/platform/service/sleeptimer/src/sl_sleeptimer_hal_timer.o 

C_DEPS += \
./gecko_sdk_4.3.0/platform/service/sleeptimer/src/sl_sleeptimer.d \
./gecko_sdk_4.3.0/platform/service/sleeptimer/src/sl_sleeptimer_hal_burtc.d \
./gecko_sdk_4.3.0/platform/service/sleeptimer/src/sl_sleeptimer_hal_prortc.d \
./gecko_sdk_4.3.0/platform/service/sleeptimer/src/sl_sleeptimer_hal_rtcc.d \
./gecko_sdk_4.3.0/platform/service/sleeptimer/src/sl_sleeptimer_hal_timer.d 


# Each subdirectory must supply rules for building sources it contributes
gecko_sdk_4.3.0/platform/service/sleeptimer/src/sl_sleeptimer.o: C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk/platform/service/sleeptimer/src/sl_sleeptimer.c gecko_sdk_4.3.0/platform/service/sleeptimer/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DBGM220PC22HNA=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD4314A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"D:\HUY\Documents\SSALab\2023\FPT IoT Challenge 2023\FPT-IoT-Challenge-2023_MSC\human_activity_recognition\config" -I"D:\HUY\Documents\SSALab\2023\FPT IoT Challenge 2023\FPT-IoT-Challenge-2023_MSC\human_activity_recognition\autogen" -I"D:\HUY\Documents\SSALab\2023\FPT IoT Challenge 2023\FPT-IoT-Challenge-2023_MSC\human_activity_recognition" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/BGM22/Include" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//app/common/util/app_timer" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/service/power_manager/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.3.0/platform/service/sleeptimer/src/sl_sleeptimer.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.3.0/platform/service/sleeptimer/src/sl_sleeptimer_hal_burtc.o: C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk/platform/service/sleeptimer/src/sl_sleeptimer_hal_burtc.c gecko_sdk_4.3.0/platform/service/sleeptimer/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DBGM220PC22HNA=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD4314A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"D:\HUY\Documents\SSALab\2023\FPT IoT Challenge 2023\FPT-IoT-Challenge-2023_MSC\human_activity_recognition\config" -I"D:\HUY\Documents\SSALab\2023\FPT IoT Challenge 2023\FPT-IoT-Challenge-2023_MSC\human_activity_recognition\autogen" -I"D:\HUY\Documents\SSALab\2023\FPT IoT Challenge 2023\FPT-IoT-Challenge-2023_MSC\human_activity_recognition" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/BGM22/Include" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//app/common/util/app_timer" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/service/power_manager/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.3.0/platform/service/sleeptimer/src/sl_sleeptimer_hal_burtc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.3.0/platform/service/sleeptimer/src/sl_sleeptimer_hal_prortc.o: C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk/platform/service/sleeptimer/src/sl_sleeptimer_hal_prortc.c gecko_sdk_4.3.0/platform/service/sleeptimer/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DBGM220PC22HNA=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD4314A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"D:\HUY\Documents\SSALab\2023\FPT IoT Challenge 2023\FPT-IoT-Challenge-2023_MSC\human_activity_recognition\config" -I"D:\HUY\Documents\SSALab\2023\FPT IoT Challenge 2023\FPT-IoT-Challenge-2023_MSC\human_activity_recognition\autogen" -I"D:\HUY\Documents\SSALab\2023\FPT IoT Challenge 2023\FPT-IoT-Challenge-2023_MSC\human_activity_recognition" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/BGM22/Include" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//app/common/util/app_timer" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/service/power_manager/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.3.0/platform/service/sleeptimer/src/sl_sleeptimer_hal_prortc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.3.0/platform/service/sleeptimer/src/sl_sleeptimer_hal_rtcc.o: C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk/platform/service/sleeptimer/src/sl_sleeptimer_hal_rtcc.c gecko_sdk_4.3.0/platform/service/sleeptimer/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DBGM220PC22HNA=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD4314A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"D:\HUY\Documents\SSALab\2023\FPT IoT Challenge 2023\FPT-IoT-Challenge-2023_MSC\human_activity_recognition\config" -I"D:\HUY\Documents\SSALab\2023\FPT IoT Challenge 2023\FPT-IoT-Challenge-2023_MSC\human_activity_recognition\autogen" -I"D:\HUY\Documents\SSALab\2023\FPT IoT Challenge 2023\FPT-IoT-Challenge-2023_MSC\human_activity_recognition" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/BGM22/Include" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//app/common/util/app_timer" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/service/power_manager/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.3.0/platform/service/sleeptimer/src/sl_sleeptimer_hal_rtcc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.3.0/platform/service/sleeptimer/src/sl_sleeptimer_hal_timer.o: C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk/platform/service/sleeptimer/src/sl_sleeptimer_hal_timer.c gecko_sdk_4.3.0/platform/service/sleeptimer/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DBGM220PC22HNA=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_BOARD_NAME="BRD4314A"' '-DSL_BOARD_REV="A02"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"D:\HUY\Documents\SSALab\2023\FPT IoT Challenge 2023\FPT-IoT-Challenge-2023_MSC\human_activity_recognition\config" -I"D:\HUY\Documents\SSALab\2023\FPT IoT Challenge 2023\FPT-IoT-Challenge-2023_MSC\human_activity_recognition\autogen" -I"D:\HUY\Documents\SSALab\2023\FPT IoT Challenge 2023\FPT-IoT-Challenge-2023_MSC\human_activity_recognition" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/BGM22/Include" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//app/common/util/app_timer" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/service/power_manager/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/anbinh/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.3.0/platform/service/sleeptimer/src/sl_sleeptimer_hal_timer.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


